
spring:
  application:
    name: user-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/counselinguser?createDatabaseIfNotExist=true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  servlet:
    context-path: /user-service
  port: 7072